name: Clipboard Linting

on: [ push, pull_request ]
jobs:
  clang-format:    
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-15
          
          sh clang-format-check.sh
  shellcheck:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          
          sh shellcheck.sh
  psscriptanalyzer:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: psscriptanalyzer
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          Invoke-ScriptAnalyzer -Path install.ps1